import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { runConformance, type Bound } from "../src/core/conformance.js";
import type { ContractFunction, ContractTest, Expectation, LibConfig, NativeSymbol, TypeNode } from "../src/core/model.js";
import { run, which } from "../src/core/shell.js";
import { exportCases, headerLines, type ExportCase, type ExportGroup } from "../src/core/testgen.js";
import { go } from "../src/languages/go/index.js";
import { goValue } from "../src/languages/go/testgen.js";

const FIXTURE = path.join(path.dirname(fileURLToPath(import.meta.url)), "fixtures", "go");
const gen = go.testgen!;

const lib = (knownFailures: Record<string, string> = {}, options: Record<string, unknown> = {}): LibConfig => ({
  name: "lib",
  language: "go",
  entry: ".",
  bindings: {},
  ignore: [],
  waivers: {},
  knownFailures,
  options,
  source: ""
});
const ctx = (l = lib()) => ({ lib: l, root: FIXTURE, workDir: os.tmpdir() });
const n = (name: string): TypeNode => ({ kind: "name", name });
const sym = (name: string, params: TypeNode[], returnsNode?: TypeNode, importPath = `example.com/fixture/${name.split(".")[0]}`): NativeSymbol =>
  ({
    name,
    params: params.map((typeNode, i) => ({ name: `p${i}`, typeNode })),
    returnsNode,
    meta: { importPath, package: name.split(".")[0], func: name.split(".")[1] }
  }) as unknown as NativeSymbol;
const isValid = sym("cpf.IsValid", [n("string")], n("bool"));

function one(expect: Expectation, extra: Partial<ExportCase> = {}): string {
  const c: ExportCase = { id: "cpf.isValid#x", fnId: "cpf.isValid", slug: ["x"], symbol: isValid, args: ["1"], expect, repeat: 1, ...extra };
  return gen.render(ctx(), [{ fnId: c.fnId, symbol: c.symbol, cases: [c] }], ["Generated by x. DO NOT EDIT.", "hdr"]).content;
}

describe("go testgen: literals", () => {
  it("expected values as Go `any` expressions", () => {
    assert.equal(goValue([1, 1.5, null, true, "a\"\n", { zip_code: "1" }, {}]), '[]any{1, 1.5, nil, true, "a\\"\\n", map[string]any{"zip_code": "1"}, map[string]any{}}');
  });
});

describe("go testgen: rendering", () => {
  it("header, package, imports and one Test func per function", () => {
    const out = one({ kind: "returns", value: true }, { note: "a\nnote" });
    assert.match(out, /^\/\/ Code generated by x\. DO NOT EDIT\.\n\/\/ hdr\n\npackage apicontract\n\nimport \(\n\t"encoding\/json"\n/);
    assert.match(out, /\n\n\t"example\.com\/fixture\/cpf"\n\)\n/);
    assert.match(out, /\/\/ cpf\.isValid -> cpf\.IsValid\nfunc TestCpfIsValid\(t \*testing\.T\) \{\n\tt\.Run\("x", func\(t \*testing\.T\) \{\n\t\t\/\/ cpf\.isValid#x\n\t\t\/\/ a note\n/);
    assert.match(out, /\t\tgot, err := call\(func\(\) \(any, error\) \{\n\t\t\treturn cpf\.IsValid\("1"\), nil\n\t\t\}\)\n\t\twantReturns\(t, got, err, true\)\n\t\}\)\n\}\n/);
  });
  it("each expectation kind", () => {
    assert.match(one({ kind: "returns", value: null }), /wantReturns\(t, got, err, nil\)/);
    assert.match(one({ kind: "returns", value: { zipCode: 1.5 } }), /wantReturns\(t, got, err, map\[string\]any\{"zipCode": 1\.5\}\)/);
    assert.match(one({ kind: "throws" }), /wantError\(t, got, err\)/);
    assert.match(one({ kind: "matches", pattern: "^\\d+$" }), /wantMatch\(t, got, err, `\^\\d\+\$`\)/);
    assert.match(one({ kind: "matches", pattern: "^a$" }), /wantMatch\(t, got, err, "\^a\$"\)/);
    const sat = one({ kind: "satisfies", fn: "cpf.isValid" }, { symbol: sym("cpf.Generate", [], n("string")), args: [], target: isValid });
    assert.match(sat, /return cpf\.Generate\(\), nil\n\t\t\}\)\n\t\twantSatisfies\(t, got, err, "cpf\.IsValid", func\(value any\) \(any, error\) \{\n\t\t\treturn cpf\.IsValid\(convert\[string\]\(t, value\)\), nil\n\t\t\}\)/);
  });
  it("uses the runner's result mapping: (T, error) and comma-ok", () => {
    const format = sym("cpf.Format", [n("string")], { kind: "tuple", of: [n("string"), n("error")] });
    assert.match(one({ kind: "throws" }, { symbol: format }), /v0, err := cpf\.Format\("1"\)\n\t\t\tif err != nil \{\n\t\t\t\treturn nil, err\n\t\t\t\}\n\t\t\treturn v0, nil\n/);
    const lookup = sym("cpf.Lookup", [n("int")], { kind: "tuple", of: [{ kind: "ref", op: "*", of: n("string") }, n("bool")] });
    assert.match(one({ kind: "returns", value: null }, { symbol: lookup, args: [1] }), /v0, v1 := cpf\.Lookup\(int\(1\)\)\n\t\t\tif !v1 \{\n\t\t\t\treturn nil, nil\n\t\t\t\}\n/);
  });
  it("skip and repeat", () => {
    const out = one({ kind: "returns", value: true }, { skip: "known failure: bug", repeat: 3 });
    assert.match(out, /\t\t\/\/ cpf\.isValid#x\n\t\tt\.Skip\("known failure: bug"\)\n\t\tfor i := 0; i < 3; i\+\+ \{\n\t\t\tgot, err := call\(func\(\) \(any, error\) \{\n\t\t\t\treturn cpf\.IsValid\("1"\), nil\n\t\t\t\}\)\n\t\t\twantReturns\(t, got, err, true\)\n\t\t\}\n\t\}\)/);
  });
  it("unexpressible cases become a comment (and their imports are left out)", () => {
    const c: ExportCase = { id: "cpf.isValid#bad", fnId: "cpf.isValid", slug: ["bad"], symbol: isValid, args: [1], expect: { kind: "returns", value: true }, repeat: 1 };
    const r = gen.render(ctx(), [{ fnId: c.fnId, symbol: c.symbol, cases: [c] }], []);
    assert.deepEqual(r.unexpressible, [{ id: "cpf.isValid#bad", reason: "expected string, got 1" }]);
    assert.match(r.content, /func TestCpfIsValid\(t \*testing\.T\) \{\n\t\/\/ cpf\.isValid#bad: not expressible in Go: expected string, got 1\n\}/);
    assert.doesNotMatch(r.content, /t\.Run\("bad"|example\.com/);
    const lookahead = gen.render(ctx(), [{ fnId: c.fnId, symbol: c.symbol, cases: [{ ...c, args: ["1"], expect: { kind: "matches", pattern: "^(?!0)" } }] }], []);
    assert.equal(lookahead.unexpressible.length, 1);
  });
  it("aliases imports whose package names collide", () => {
    const a = sym("cpf.IsValid", [n("string")], n("bool"), "example.com/a/cpf");
    const b = sym("cpf.Format", [n("string")], n("string"), "example.com/b/cpf");
    const out = gen.render(ctx(), [
      { fnId: "cpf.isValid", symbol: a, cases: [{ id: "cpf.isValid#x", fnId: "cpf.isValid", slug: ["x"], symbol: a, args: ["1"], expect: { kind: "returns", value: true }, repeat: 1 }] },
      { fnId: "cpf.format", symbol: b, cases: [{ id: "cpf.format#x", fnId: "cpf.format", slug: ["x"], symbol: b, args: ["1"], expect: { kind: "returns", value: "1" }, repeat: 1 }] }
    ], []).content;
    assert.match(out, /\tacpf "example\.com\/a\/cpf"\n\tbcpf "example\.com\/b\/cpf"\n/);
    assert.match(out, /acpf\.IsValid\("1"\)/);
    assert.match(out, /bcpf\.Format\("1"\)/);
  });
  it("is deterministic, and the path/command are the lib's", () => {
    assert.equal(one({ kind: "throws" }), one({ kind: "throws" }));
    assert.equal(gen.path(ctx()), "apicontract/api_contract_test.go");
    assert.equal(gen.command(ctx()), "go test ./apicontract");
    const custom = ctx(lib({}, { testFile: "cpf/contract_test.go" }));
    assert.equal(gen.command(custom), "go test ./cpf");
    assert.match(gen.render(custom, [], []).content, /\npackage cpf_test\n/); // external test package of cpf
  });
});

/** Extra package written into the temp copy only (the shared fixture's symbol list stays as is). */
const DEMO = `package demo

type Address struct {
	ZipCode string
	Other   *string
}

func Addr(zip string) Address { return Address{ZipCode: zip} }

func Ratio() float64 { return 1.5000000000001 }

func Generate() string { return "12345678901" }

func Short() string { return "1" }

func Panics() string { panic("boom") }

func Codes() []int { return []int{1, 2} }
`;

describe("go testgen: fixture", () => {
  it("native `go test` results match the validator", { skip: !which("go") && "no go", timeout: 240_000 }, async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "testgen-go-"));
    fs.cpSync(FIXTURE, dir, { recursive: true });
    fs.mkdirSync(path.join(dir, "demo"));
    fs.writeFileSync(path.join(dir, "demo", "demo.go"), DEMO);
    const l = lib({ "cpf.format#known": "demo bug" });
    const c = { lib: l, root: dir, workDir: fs.mkdtempSync(path.join(os.tmpdir(), "testgen-go-work-")) };
    const { symbols } = await go.extract(c);
    const byName = new Map(symbols.map((s) => [s.name, s]));
    const t = (fnId: string, name: string, args: unknown[], expect: Expectation, repeat = 1): ContractTest => ({ id: `${fnId}#${name}`, name, args, expect, repeat });
    const fn = (id: string, symbol: string, tests: ContractTest[]): Bound => {
      assert.ok(byName.get(symbol), symbol);
      return {
        fn: { id, domain: id.split(".")[0], operation: id.split(".")[1], flatName: id, spellings: [], level: "core", params: [], returns: "any", tests, source: "" } as unknown as ContractFunction,
        symbol: byName.get(symbol)!
      };
    };
    const bound = [
      fn("cpf.isValid", "cpf.IsValid", [
        t("cpf.isValid", "eleven", ["12345678901"], { kind: "returns", value: true }),
        t("cpf.isValid", "one", ["1"], { kind: "returns", value: false }),
        t("cpf.isValid", "wrong", ["1"], { kind: "returns", value: true }),
        t("cpf.isValid", "number", [1], { kind: "returns", value: false }),
        t("cpf.isValid", "no-args", [], { kind: "throws" })
      ]),
      fn("cpf.format", "cpf.Format", [
        t("cpf.format", "same", ["12345678901"], { kind: "returns", value: "12345678901" }),
        t("cpf.format", "short", ["1"], { kind: "throws" }),
        t("cpf.format", "short-null", ["1"], { kind: "returns", value: null }),
        t("cpf.format", "no-error", ["12345678901"], { kind: "throws" }),
        t("cpf.format", "known", ["1"], { kind: "returns", value: "x" })
      ]),
      fn("cpf.lookup", "cpf.Lookup", [t("cpf.lookup", "absent", [1], { kind: "returns", value: null })]),
      fn("cpf.join", "cpf.Join", [
        t("cpf.join", "rest", ["-", "a", "b"], { kind: "returns", value: "-" }),
        t("cpf.join", "dash", ["-", "a"], { kind: "matches", pattern: "^-$" }),
        t("cpf.join", "not-x", ["-"], { kind: "matches", pattern: "^x" })
      ]),
      fn("demo.addr", "demo.Addr", [
        t("demo.addr", "keys", ["1"], { kind: "returns", value: { zip_code: "1" } }),
        t("demo.addr", "other-null", ["1"], { kind: "returns", value: { zipCode: "1", other: null } }),
        t("demo.addr", "differs", ["1"], { kind: "returns", value: { zipCode: "2" } })
      ]),
      fn("demo.ratio", "demo.Ratio", [
        t("demo.ratio", "close", [], { kind: "returns", value: 1.5 }),
        t("demo.ratio", "far", [], { kind: "returns", value: 1.6 })
      ]),
      fn("demo.generate", "demo.Generate", [t("demo.generate", "valid", [], { kind: "satisfies", fn: "cpf.isValid" }, 3)]),
      fn("demo.short", "demo.Short", [t("demo.short", "invalid", [], { kind: "satisfies", fn: "cpf.isValid" })]),
      fn("demo.panics", "demo.Panics", [
        t("demo.panics", "throws", [], { kind: "throws" }),
        t("demo.panics", "returns", [], { kind: "returns", value: "x" })
      ]),
      fn("demo.codes", "demo.Codes", [
        t("demo.codes", "list", [], { kind: "returns", value: [1, 2] }),
        t("demo.codes", "short-list", [], { kind: "returns", value: [1] })
      ])
    ];
    const boundById = new Map(bound.map((b) => [b.fn.id, b.symbol]));
    const groups: ExportGroup[] = exportCases(bound, boundById, l);
    const rendered = gen.render(c, groups, headerLines(l, groups, gen.command(c)));
    assert.deepEqual(rendered.unexpressible.map((u) => u.id).sort(), ["cpf.isValid#no-args", "cpf.isValid#number"]);
    fs.mkdirSync(path.join(dir, "apicontract"));
    fs.writeFileSync(path.join(dir, gen.path(c)), rendered.content);

    const env = { ...process.env, GOWORK: "off", GOTOOLCHAIN: "local", GOFLAGS: "" };
    assert.equal(run("gofmt", ["-l", gen.path(c)], { cwd: dir, env }).stdout, "", "gofmt-clean");
    assert.equal(run("go", ["vet", "./apicontract"], { cwd: dir, env }).status, 0, "go vet clean");
    const r = run("go", ["test", "-json", "./apicontract"], { cwd: dir, env });
    const native = new Map<string, string>();
    for (const line of r.stdout.split("\n").filter(Boolean)) {
      const e = JSON.parse(line) as { Action: string; Test?: string };
      if (e.Test?.includes("/") && ["pass", "fail", "skip"].includes(e.Action)) native.set(e.Test.split("/")[1], e.Action);
    }

    const validator = new Map([...(await runConformance(bound, boundById, l, go, c)).values()].flat().map((o) => [o.id.split("#")[1], o.status]));
    const expected = new Map<string, string>();
    for (const [name, status] of validator) {
      if (status === "skip") continue; // unsupported by the runner = not expressible in the file
      expected.set(name.replace(/-/g, "_"), status === "known-failure" ? "skip" : status);
    }
    assert.deepEqual(Object.fromEntries([...native].sort()), Object.fromEntries([...expected].sort()));
    assert.deepEqual(
      [...native].filter(([, s]) => s === "fail").map(([n]) => n).sort(),
      ["differs", "far", "invalid", "no_error", "not_x", "returns", "short_list", "short_null", "wrong"]
    );
  });
});
