import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { glob } from 'astro/loaders';
import { docsLoader, i18nLoader } from '@astrojs/starlight/loaders';
import { docsSchema, i18nSchema } from '@astrojs/starlight/schema';

export const collections = {
  // Site pages (src/content/docs). Utility pages are generated there by scripts/generate-pages.mjs.
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),

  // UI strings. Built-in Starlight keys plus the custom ones used by our components.
  i18n: defineCollection({
    loader: i18nLoader(),
    schema: i18nSchema({
      extend: z
        .object({
          'util.implementedIn': z.string(),
          'util.related': z.string(),
          'util.guides': z.string(),
          'util.count': z.string(),
          'util.since': z.string(),
          'util.guideFrom': z.string(),
          'spec.fallback': z.string(),
          'references.none': z.string(),
          'references.localCopy': z.string(),
          'usage.notAvailable': z.string(),
          'usage.contribute': z.string(),
          'usage.document': z.string(),
          'usage.undocumented': z.string(),
          'usage.source': z.string(),
          'testcases.none': z.string(),
          'testcases.input': z.string(),
          'testcases.expected': z.string(),
          'parity.utility': z.string(),
          'parity.legend': z.string(),
          'parity.full': z.string(),
          'parity.partial': z.string(),
          'parity.failing': z.string(),
          'parity.none': z.string(),
          'parity.fetchedAt': z.string(),
          'parity.fromRun': z.string(),
          'ops.englishOnly': z.string(),
          'ops.network': z.string(),
          'ops.deprecated': z.string(),
          'status.label': z.string(),
          'status.ok': z.string(),
          'status.failing': z.string(),
          'status.signature': z.string(),
          'status.missing': z.string(),
          'status.waived': z.string(),
          'status.short.failing': z.string(),
          'status.short.signature': z.string(),
          'status.short.missing': z.string(),
          'status.failedCases_one': z.string(),
          'status.failedCases_other': z.string(),
          'cases.summary': z.string(),
          'cases.notRun': z.string(),
          'cases.pass': z.string(),
          'cases.fail': z.string(),
          'cases.known-failure': z.string(),
          'cases.skip': z.string(),
          'lib.noStatus': z.string(),
          'lib.repository': z.string(),
          'lib.package': z.string(),
          'lib.badge': z.string(),
          'lib.badgeAlt': z.string(),
          'lib.summary': z.string(),
          'lib.summaryCases': z.string(),
          'lib.summarySignatures': z.string(),
          'lib.summaryOutside': z.string(),
          'lib.core': z.string(),
          'lib.coreTag': z.string(),
          'lib.implemented': z.string(),
          'lib.passing': z.string(),
          'lib.compare': z.string(),
          'lib.library': z.string(),
          'lib.work': z.string(),
          'lib.workIntro': z.string(),
          'lib.workDone': z.string(),
          'lib.function': z.string(),
          'lib.status': z.string(),
          'lib.why': z.string(),
          'lib.implementedBy': z.string(),
          'lib.nobody': z.string(),
          'lib.maybe': z.string(),
          'lib.failures': z.string(),
          'lib.case': z.string(),
          'lib.actual': z.string(),
          'lib.undocumented': z.string(),
          'lib.undocumentedIntro': z.string(),
          'lib.outsideTitle': z.string(),
          'lib.outsideIntro': z.string(),
          'guide.from': z.string(),
          'guide.source': z.string(),
          'guide.englishOnly': z.string(),
          'guide.uses': z.string(),
          'guide.liveDemo': z.string(),
          'guide.liveDemoOf': z.string(),
          'guide.openDemo': z.string(),
          'try.title': z.string(),
          'try.run': z.string(),
          'try.hint': z.string(),
          'try.note': z.string(),
          'try.matches': z.string(),
          'try.differs': z.string(),
          'specimen.label': z.string(),
          'specimen.examples': z.string(),
          'specimen.valid': z.string(),
          'specimen.invalid': z.string(),
          'specimen.unknown': z.string(),
          'specimen.checkDigits_one': z.string(),
          'specimen.checkDigits_other': z.string(),
          'specimen.sameCheck': z.string(),
          'libs.language': z.string(),
          'libs.install': z.string(),
          'libs.coverage': z.string(),
          'libs.coverageValue': z.string(),
          'libs.source': z.string(),
        })
        .partial(),
    }),
  }),

  // Long-form specs next to the contract: contract/<domain>/spec.en.md and spec.pt-BR.md.
  // Entry ids look like "cpf/en" and "licensePlate/pt-BR".
  specs: defineCollection({
    loader: glob({
      pattern: '*/spec.*.md',
      base: '../contract',
      generateId: ({ entry }) => {
        const [domain, file] = entry.split('/');
        return `${domain}/${file === 'spec.en.md' ? 'en' : 'pt-BR'}`;
      },
    }),
    schema: z.object({
      id: z.string().optional(),
      title: z.string().optional(),
      language: z.string().optional(),
      references: z.array(z.string()).optional(),
    }),
  }),

  // Usage snippets downloaded from each library repo by scripts/fetch-libs.mjs.
  // One entry per (lib, util, operation[, locale]).
  usage: defineCollection({
    loader: glob({ pattern: '**/*.md', base: './.cache/usage' }),
    schema: z.object({
      lib: z.string(),
      util: z.string(),
      op: z.string(),
      locale: z.enum(['en', 'pt-BR']).default('en'),
      since: z.string().optional(),
      source: z.string().optional(),
    }),
  }),
};
