/**
 * Exported contract tests: the shared test vectors rendered as a native test file of each
 * lib (unittest, vitest, `go test`, `cargo test`, RSpec, EUnit, xUnit), committed to the
 * lib and run by its own test command, with no dependency on this repository.
 *
 * The validator stays the independent check (API matching, public surface, differential
 * testing, the cross-lib view); the exported file puts the same vectors where the lib's
 * developers already look, fails their `test` command on the spot, and documents the
 * expected behaviour in their language. `export-tests --check` in the lib's CI fails when
 * the file is stale, so the two never drift.
 *
 * Only functions the lib implements with a compatible signature are exported. Tests the lib
 * does not pass yet (knownFailures, or not in its baseline) are emitted as skipped, with
 * the reason, so the lib's suite is green on adoption and each fix un-skips a test.
 */
import crypto from "node:crypto";
import type { Bound } from "./conformance.js";
import type { Baseline } from "./baseline.js";
import type { ContractTest, Expectation, LibConfig, NativeSymbol } from "./model.js";
import { words } from "./naming.js";

export interface ExportCase {
  /** Stable contract test id, e.g. `cpf.isValid#valid-sample`. */
  id: string;
  fnId: string;
  /** Words naming the test inside its function (for native test names). */
  slug: string[];
  symbol: NativeSymbol;
  args: unknown[];
  expect: Expectation;
  repeat: number;
  /** Bound symbol of the `satisfies` target. */
  target?: NativeSymbol;
  /** Emit as skipped, with this reason. */
  skip?: string;
  note?: string;
}

export interface ExportGroup {
  fnId: string;
  symbol: NativeSymbol;
  cases: ExportCase[];
}

/** Case the generator could not express in its language (reported, and left as a comment). */
export interface Unexpressible {
  id: string;
  reason: string;
}

export interface Rendered {
  content: string;
  unexpressible: Unexpressible[];
}

/** Words for a test within its function: its `name`, else its arguments. */
export function slugOf(test: ContractTest): string[] {
  const raw = test.name ?? test.id.slice(test.id.indexOf("#") + 1);
  let w = words(raw.replace(/[^A-Za-z0-9]+/g, " ")).map((x) => x.toLowerCase());
  if (w.length === 0) w = ["empty"];
  if (w.join("_").length > 48) {
    const hash = crypto.createHash("sha256").update(test.id).digest("hex").slice(0, 8);
    let kept: string[] = [];
    for (const x of w) {
      if ([...kept, x].join("_").length > 36) break;
      kept.push(x);
    }
    if (kept.length === 0) kept = [w[0].slice(0, 36)];
    w = [...kept, hash];
  }
  return w;
}

export function exportCases(bound: Bound[], boundById: Map<string, NativeSymbol>, lib: LibConfig, baseline?: Baseline): ExportGroup[] {
  const passing = baseline && baseline.tests.length > 0 ? new Set(baseline.tests) : undefined;
  const groups: ExportGroup[] = [];
  for (const { fn, symbol } of [...bound].sort((a, b) => a.fn.id.localeCompare(b.fn.id))) {
    if (fn.network) continue;
    const cases: ExportCase[] = [];
    const seen = new Map<string, number>();
    for (const test of fn.tests) {
      const target = test.expect.kind === "satisfies" ? boundById.get(test.expect.fn) : undefined;
      if (test.expect.kind === "satisfies" && !target) continue;
      let slug = slugOf(test);
      const key = slug.join("_");
      const n = seen.get(key) ?? 0;
      seen.set(key, n + 1);
      if (n > 0) slug = [...slug, String(n + 1)];
      const known = lib.knownFailures[test.id] ?? lib.knownFailures[fn.id];
      const skip = known
        ? `known failure: ${known}`
        : passing && !passing.has(test.id)
          ? "fails today (not in the api-validator baseline): see the lib's sync issue"
          : undefined;
      cases.push({ id: test.id, fnId: fn.id, slug, symbol, args: test.args, expect: test.expect, repeat: test.repeat, target, skip, note: test.note });
    }
    if (cases.length) groups.push({ fnId: fn.id, symbol, cases });
  }
  return groups;
}

/** Digest of what the file encodes: changes exactly when the exported tests change. */
export function casesDigest(groups: ExportGroup[]): string {
  const data = groups.flatMap((g) =>
    g.cases.map((c) => [c.id, c.symbol.name, c.args, c.expect, c.repeat, c.target?.name ?? null, c.skip ?? null])
  );
  return crypto.createHash("sha256").update(JSON.stringify(data)).digest("hex").slice(0, 16);
}

export function headerLines(lib: LibConfig, groups: ExportGroup[], command: string): string[] {
  const tests = groups.reduce((n, g) => n + g.cases.length, 0);
  const skipped = groups.reduce((n, g) => n + g.cases.filter((c) => c.skip).length, 0);
  return [
    "Generated by brazilian-utils/api-validator from the shared contract. DO NOT EDIT.",
    `${tests} tests of ${groups.length} functions (${skipped} skipped), digest ${casesDigest(groups)}.`,
    "Fix behaviour in the lib, and expectations in api-validator/contract; then regenerate:",
    `  npx tsx <api-validator>/src/cli.ts export-tests --lib ${lib.name} --path .`,
    `Run: ${command}`
  ];
}

/** Every test of every group, in order: the list generators iterate. */
export function allCases(groups: ExportGroup[]): ExportCase[] {
  return groups.flatMap((g) => g.cases);
}
